name: Build and Deploy

# 向主干 main 分支推送代码时触发部署
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: 安装 pnpm
        uses: pnpm/action-setup@v3
        with:
          version: '11.25.0' # 指定 pnpm 版本，建议与本地使用的版本保持一致
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.21.0' # 选择适合的 Node.js 版本
          cache: 'pnpm' # 自动基于 pnpm-lock.yaml 启用依赖缓存
      
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      
      - name: Build project
        run: npm run build:web
      
      # 使用密码将打包好的文件通过 SCP 上传到服务器
      - name: Upload dist to Server via Password
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.LOGIN_NAME }}
          password: ${{ secrets.LOGIN_PASSWORD }}
          source: "dist/web/*"                  # 本地要上传的文件夹路径
          target: "/var/www/${{ secrets.SERVER_NAME }}"         # 服务器上的目标目录
          strip_components: 1               # 过滤掉顶层的 "dist/" 文件夹，直接将内容解压到 target 目录
          rm: true                          # 类似 --delete，上传前自动清空目标目录下的旧文件
      
      # 新增步骤：通过 SSH 重载/重启 Nginx
      - name: Reload Nginx Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.LOGIN_NAME }}
          password: ${{ secrets.LOGIN_PASSWORD }}
          script: |
            sudo nginx -t && sudo systemctl reload nginx